"""requirement review fields and finding rule pack stamp

Revision ID: 06b186e54f3b
Revises: 624379438e5d
Create Date: 2026-09-02 13:51:24.408767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06b186e54f3b'
down_revision: Union[str, Sequence[str], None] = '624379438e5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('findings', sa.Column('rule_pack_name', sa.String(length=128), nullable=True))
    op.add_column('findings', sa.Column('rule_pack_version', sa.Integer(), nullable=True))
    op.add_column('findings', sa.Column('rule_pack_sha256', sa.String(length=64), nullable=True))
    op.add_column('findings', sa.Column('engine_version', sa.String(length=32), nullable=True))
    op.add_column('requirements', sa.Column('reviewed_by', sa.String(length=256), nullable=True))
    op.add_column('requirements', sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('requirements', 'reviewed_at')
    op.drop_column('requirements', 'reviewed_by')
    op.drop_column('findings', 'engine_version')
    op.drop_column('findings', 'rule_pack_sha256')
    op.drop_column('findings', 'rule_pack_version')
    op.drop_column('findings', 'rule_pack_name')
    # ### end Alembic commands ###
