"""initial schema

Revision ID: 624379438e5d
Revises:
Create Date: 2026-08-29 21:32:56.600137

Hand-authored rather than autogenerated: no live Postgres was reachable in the
environment this was written in. Creates every table from app.models via the
shared SQLAlchemy metadata, so it stays in sync with the ORM models by
construction. Once a real database is available, run `alembic upgrade head`
to apply it; future schema changes should go back to normal autogenerate
revisions (`alembic revision --autogenerate`) layered on top of this one.
"""
from typing import Sequence, Union

from alembic import op

from app import models  # noqa: F401 - registers all tables on Base.metadata
from app.db.base import Base

# revision identifiers, used by Alembic.
revision: str = '624379438e5d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    Base.metadata.create_all(bind=op.get_bind())


def downgrade() -> None:
    """Downgrade schema."""
    Base.metadata.drop_all(bind=op.get_bind())
